name: 'Deploy to AWS CloudFormation'

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code from master branch
        uses: actions/checkout@v4

      # Configure AWS Credential
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: us-east-1

      # Deploy to AWS CloudFormation
      # - name: Deploy baseline VPC
      #   uses: aws-actions/aws-cloudformation-github-deploy@v1
      #   with:
      #     name: sandbox-stack
      #     template: sandbox-stack.yml
      #     no-fail-on-empty-changeset: "1"

      # - name: Deploy basic webserver stack
      #   uses: aws-actions/aws-cloudformation-github-deploy@v1
      #   with:
      #     name: webserver-stack
      #     template: webserver/webserver-stack.yml
      #     no-fail-on-empty-changeset: "1"
      #     parameter-overrides: "InstanceType=t2.micro,KeyName=aws-sandbox"