services:
  ngrok:
    image: ngrok/ngrok:3
    restart: unless-stopped
    env_file:
      - .env
      - .secrets
    command:
    - "http"
    - "${JENKINS_URL}"
    - "--verify-webhook" 
    - "github" 
    - "--verify-webhook-secret"
    - "${GITHUB_WEBHOOK_SECRET}"
    - "--log"
    - "stdout"
    - "--log-format"
    - "json"
    - "--log-level"
    - "info"
    - "--domain=${NGROK_DOMAIN}"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - 4040:4040
