apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      APPLICATION: ngrok
      ENVIRONMENT: prd
  template:
    metadata:
      labels:
        APPLICATION: ngrok
        ENVIRONMENT: prd
    spec:
      containers:
      - name: ngrok
        image: ngrok/ngrok:3
        command: [ "/bin/ngrok" ]
        args: [ "http", "$(JENKINS_URL)", "--verify-webhook" , "github" , "--verify-webhook-secret", "$(GITHUB_WEBHOOK_SECRET)", "--log", "stdout", "--log-format", "json", "--log-level", "info", "--domain=$(NGROK_DOMAIN)" ]
        env:
          - name: GITHUB_WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: ngrok
                key: GITHUB_WEBHOOK_SECRET
          - name: NGROK_AUTHTOKEN
            valueFrom:
              secretKeyRef:
                name: ngrok
                key: NGROK_AUTHTOKEN
          - name: JENKINS_URL
            valueFrom:
              configMapKeyRef:
                name: ngrok
                key: JENKINS_URL
          - name: NGROK_DOMAIN
            valueFrom:
              configMapKeyRef:
                name: ngrok
                key: NGROK_DOMAIN
