apiVersion: v1
kind: Service
metadata:
  name: ngrok
  labels:
    APPLICATION: ngrok
    ENVIRONMENT: prd
spec:
  type: LoadBalancer
  ports:
  - port: 4040
    targetPort: 4040
  selector:
    APPLICATION: ngrok
    ENVIRONMENT: prd
---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      APPLICATION: ngrok
      ENVIRONMENT: prd
  template:
    metadata:
      labels:
        APPLICATION: ngrok
        ENVIRONMENT: prd
    spec:
      containers:
      - name: ngrok
        image: ngrok/ngrok:latest
        command: [ "/bin/ngrok" ]
        args: [ "http", "$(JENKINS_URL)", "--verify-webhook", "github", "--verify-webhook-secret", "$(GITHUB_WEBHOOK_SECRET)" ]
        env:
          - name: GITHUB_WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: ngrok
                key: GITHUB_WEBHOOK_SECRET
          - name: JENKINS_URL
            valueFrom:
              secretKeyRef:
                name: ngrok
                key: JENKINS_URL
          - name: NGROK_AUTHTOKEN
            valueFrom:
              secretKeyRef:
                name: ngrok
                key: NGROK_AUTHTOKEN
        ports:
          - containerPort: 4040
            hostPort: 4040