AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon EKS cluster control plane

Parameters:
  ClusterName:
    Default: eks-cluster
    Description: Name of EKS Cluster
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9\-\_]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters, hypnens, and underscores.
  Environment:
    Description: Application Environment
    Default: prd
    Type: String
    AllowedValues: ["prd", "stg", "tst", "dev"]
    ConstraintDescription: 'Must be one of: "prd", "stg", "tst", "dev"'
  VPC:
    Type: 'AWS::EC2::VPC::Id'
    Description: A virtual private cloud that enables resources in the public subnets to connect to the Internet
  Subnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: At least two public and two private subnets in different Availability Zones in the selected VPC
  NodeInstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - m1.small
      - m3.medium
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
    ConstraintDescription: Must be a valid EC2 instance type
    Description: EC2 instance type for the node instances
    
Resources:
  EKSIAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      RoleName: !Sub ${ClusterName}-ekscluster-role
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy
  ControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Cluster communication with worker nodes
      VpcId: !Ref VPC
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      RoleArn:
        "Fn::GetAtt": ["EKSIAMRole", "Arn"]
      ResourcesVpcConfig:
        SecurityGroupIds:
        - !Ref ControlPlaneSecurityGroup
        SubnetIds: !Ref Subnets

  NodeInstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      RoleName: !Sub ${ClusterName}-eksnodeinstance-role
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
        - "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
        - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
      Path: /
  EKSNodegroup:
    Type: 'AWS::EKS::Nodegroup'
    Properties:
      ClusterName: !Ref EKSCluster
      NodeRole: !GetAtt NodeInstanceRole.Arn
      InstanceTypes: [ !Ref NodeInstanceType ]
      ScalingConfig:
        MinSize: 1
        DesiredSize: 2
        MaxSize: 4
      Subnets: !Ref Subnets
      Tags:
        APPLICATION: !Ref ClusterName
        ENVIRONMENT: !Ref Environment

Outputs:
  ClusterControlPlaneSecurityGroup:
    Value: !Ref ControlPlaneSecurityGroup
    Description: The security group of the cluster control plane.
  ClusterName:
    Value: !Ref EKSCluster
    Description: The cluster name provided when the cluster was created.
